export default {
    MAIN_CONTENTS: 'MAIN-CONTENTS',
    ROOT_COMMENTS: 'ROOT-COMMENTS',
    MAX_COMMENT_ID: 'MAX-COMMENT-ID',
    COMMENT_CONTENT_PREFIX: 'COMMENT-CONTENT-PREFIX',
    COMMENT_LIST_PREFIX: 'COMMENT-CONTENT-PREFIX'
}